[[IgnoredVulns]]
id = "EEF-CVE-2026-43968"
reason = "App does not use Server-Sent Events"

[[IgnoredVulns]]
id = "EEF-CVE-2026-43969"
reason = "App makes no outbound HTTP requests with user-controlled cookies"

[[IgnoredVulns]]
id = "EEF-CVE-2026-32686"
reason = "App does not use the Decimal library"
