defmodule PenguinMemories.Upload do
  @moduledoc """
  Upload new media objects.

  Core design decisions:
  - DB insert and file copy are wrapped in an Ecto.Multi transaction so that a
    failure at any step rolls back the Photo row, preventing dangling DB entries.
  - SHA-256 / num_bytes dedup means re-running the same directory is safe and
    idempotent: already-imported files are skipped.
  - CR2/CR3 sidecars are attached to the same Photo as the paired JPG.
  - action: "R" is set on every uploaded photo so thumbnails are generated by
    the background processor (Actions.process_pending/1).
  - Optionally action: "auto" can be requested via :auto_rotate, which causes
    the background processor to losslessly rotate the JPEG before thumbnailing.
  """
  import Bitwise
  import Ecto.Query
  import File

  alias Ecto.Multi
  alias Logger
  require Logger
  alias PenguinMemories.Database.Conflicts
  alias PenguinMemories.Media
  alias PenguinMemories.Photos.Album
  alias PenguinMemories.Photos.AlbumParent
  alias PenguinMemories.Photos.File
  alias PenguinMemories.Photos.Photo
  alias PenguinMemories.Repo
  alias PenguinMemories.Storage

  # ---------------------------------------------------------------------------
  # EXIF / camera helpers
  # ---------------------------------------------------------------------------

  @spec get_camera_offset(String.t() | nil) :: {String.t(), integer()}
  defp get_camera_offset(nil), do: {"Etc/UTC", 0}

  defp get_camera_offset(camera_model) do
    cameras = Application.get_env(:penguin_memories, :cameras)
    {timezone, string} = Map.fetch!(cameras, camera_model)

    [hh, mm, ss] = String.split(string, ":")

    {hh, ""} = Integer.parse(hh)
    {mm, ""} = Integer.parse(mm)
    {ss, ""} = Integer.parse(ss)

    {timezone, (hh * 60 + mm) * 60 + ss}
  end

  @spec metering_mode(integer() | nil) :: String.t() | nil
  defp metering_mode(nil), do: nil

  defp metering_mode(mode) do
    modes = %{
      0 => "unknown",
      1 => "average",
      2 => "center weighted average",
      3 => "spot",
      4 => "multi spot",
      5 => "pattern",
      6 => "partial",
      255 => "other"
    }

    Map.get(modes, mode, "reserved")
  end

  @spec flash_used(integer() | nil) :: boolean() | nil
  defp flash_used(nil), do: nil

  defp flash_used(mode) do
    cond do
      is_nil(mode) -> nil
      (mode &&& 1) != 0 -> true
      true -> false
    end
  end

  @spec float(String.t() | integer() | float() | nil) :: float() | nil
  defp float(nil), do: nil

  defp float(number) do
    cond do
      number == "inf" -> nil
      number == "undef" -> nil
      is_nil(number) -> nil
      is_integer(number) -> number * 1.0
      is_float(number) -> number
    end
  end

  @spec get(map(), String.t()) :: any() | nil
  def get(exif, key) do
    case Map.get(exif, key) do
      "" -> nil
      nil -> nil
      value -> value
    end
  end

  @spec add_exif_to_photo(Photo.t(), Media.t()) :: Photo.t()
  def add_exif_to_photo(%Photo{} = photo, %Media{} = media) do
    exif = Media.get_exif(media)

    latitude = get(exif, "Composite:GPSLatitude")
    longitude = get(exif, "Composite:GPSLongitude")

    point =
      if latitude != nil and longitude != nil do
        %Geo.Point{coordinates: {latitude, longitude}, srid: 4326}
      else
        nil
      end

    %Photo{
      photo
      | camera_make: get(exif, "EXIF:Make"),
        camera_model: get(exif, "EXIF:Model"),
        flash_used: get(exif, "EXIF:Flash") |> flash_used(),
        focal_length: get(exif, "EXIF:FocalLength") |> float(),
        exposure_time: get(exif, "EXIF:ExposureTime") |> float(),
        aperture: get(exif, "EXIF:FNumber") |> float(),
        iso_equiv: get(exif, "EXIF:ISO"),
        metering_mode: get(exif, "EXIF:MeteringMode") |> metering_mode(),
        focus_dist: get(exif, "Composite:HyperfocalDistance") |> float(),
        ccd_width: nil,
        point: point
    }
  end

  @type rc :: {:ok, Photo.t()} | {:skipped, Photo.t()} | {:error, String.t()}

  @spec changeset_error_to_string(Ecto.Changeset.t()) :: String.t()
  defp changeset_error_to_string(%Ecto.Changeset{} = changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Enum.reduce(opts, msg, fn {key, value}, acc ->
        String.replace(acc, "%{#{key}}", to_string(value))
      end)
    end)
    |> Enum.reduce("", fn {k, v}, acc ->
      joined_errors = Enum.join(v, "; ")
      "#{acc}#{k}: #{joined_errors}\n"
    end)
  end

  @spec add_item(list(map()), map(), (map(), map() -> boolean)) :: list(map())
  def add_item([], new_item, _), do: [new_item]

  def add_item([head | tail] = list, new_item, match?) do
    if match?.(head, new_item) do
      list
    else
      [head | add_item(tail, new_item, match?)]
    end
  end

  # ---------------------------------------------------------------------------
  # Deduplication
  # ---------------------------------------------------------------------------

  @spec check_file_conflicts(rc(), Media.t(), String.t()) :: rc()
  defp check_file_conflicts({:ok, %Photo{}} = rc, media, size_key) do
    case Conflicts.get_file_hash_conflict(media, size_key) do
      nil -> rc
      %Photo{} = photo -> {:skipped, photo}
    end
  end

  # ---------------------------------------------------------------------------
  # Transactional photo + file creation
  #
  # The Photo row and its associated orig File record are written inside a
  # single Ecto.Multi / Repo.transaction so that a file-copy failure rolls
  # back the Photo insert. This prevents dangling DB rows that have no files.
  # ---------------------------------------------------------------------------

  @spec build_photo_multi(Photo.t(), Album.t(), Media.t(), String.t()) ::
          {:ok, Photo.t()} | {:error, String.t()}
  defp build_photo_multi(%Photo{} = photo, %Album{} = album, %Media{} = media, size_key) do
    multi =
      Multi.new()
      |> Multi.insert(:photo, fn _ ->
        photo
        |> Ecto.Changeset.change()
        |> Ecto.Changeset.put_assoc(:albums, [album])
        |> Ecto.Changeset.put_assoc(:files, [])
        |> Ecto.Changeset.put_assoc(:photo_relations, [])
      end)
      |> Multi.run(:file_metadata, fn _repo, %{photo: inserted_photo} ->
        case Storage.build_file_metadata(media, inserted_photo, size_key, check_conflicts: true) do
          {:ok, file, dest_path} -> {:ok, {file, dest_path}}
          {:error, reason} -> {:error, reason}
        end
      end)

    case Repo.transaction(multi) do
      {:ok, %{photo: inserted_photo, file_metadata: {file, dest_path}}} ->
        copy_file_and_insert_record(inserted_photo, file, media, dest_path)

      {:error, :photo, %Ecto.Changeset{} = cs, _} ->
        {:error, changeset_error_to_string(cs)}

      {:error, :file_metadata, {:error, reason}, _} ->
        {:error, reason}

      {:error, _op, _val, _acc} ->
        {:error, "transaction failed"}
    end
  end

  @spec copy_file_and_insert_record(Photo.t(), File.t(), Media.t(), String.t()) ::
          {:ok, Photo.t()} | {:error, String.t()}
  defp copy_file_and_insert_record(
         %Photo{} = inserted_photo,
         %File{} = file,
         %Media{} = media,
         dest_path
       ) do
    with :ok <- Storage.copy_file(media, dest_path),
         {:ok, _} <- insert_file_record(file, inserted_photo) do
      {:ok, reload_photo_with_file(inserted_photo)}
    else
      {:error, reason} ->
        Repo.delete!(inserted_photo)
        Storage.delete_file(dest_path)
        {:error, reason}
    end
  end

  @spec insert_file_record(File.t(), Photo.t()) :: {:ok, File.t()} | {:error, String.t()}
  defp insert_file_record(%File{} = file, %Photo{} = photo) do
    file =
      %File{
        size_key: file.size_key,
        width: file.width,
        height: file.height,
        dir: file.dir,
        filename: file.filename,
        is_video: file.is_video,
        mime_type: file.mime_type,
        sha256_hash: file.sha256_hash,
        num_bytes: file.num_bytes,
        photo_id: photo.id
      }
      |> Ecto.Changeset.change()

    case Repo.insert(file) do
      {:ok, inserted_file} -> {:ok, inserted_file}
      {:error, cs} -> {:error, changeset_error_to_string(cs)}
    end
  end

  @spec reload_photo_with_file(Photo.t()) :: Photo.t()
  defp reload_photo_with_file(%Photo{} = photo) do
    Photo
    |> where(id: ^photo.id)
    |> preload([:albums, :files, :photo_relations])
    |> Repo.one!()
  end

  # ---------------------------------------------------------------------------
  # Attaching additional files (raw sidecar) to an already-saved Photo
  # ---------------------------------------------------------------------------

  @spec raw_extensions() :: list(String.t())
  defp raw_extensions, do: [".CR2", ".cr2", ".CR3", ".cr3"]

  @spec add_raw_files(rc(), String.t()) :: rc()
  defp add_raw_files({:error, _} = err, _path), do: err
  defp add_raw_files({:skipped, %Photo{}} = rc, _path), do: rc

  defp add_raw_files({:ok, %Photo{} = photo}, path) do
    base = Path.join(Path.dirname(path), Path.basename(path, Path.extname(path)))

    raw_file =
      raw_extensions()
      |> Enum.map(fn ext -> base <> ext end)
      |> Enum.find(&exists?/1)

    if raw_file == nil do
      {:ok, photo}
    else
      case Media.get_media(raw_file) do
        {:ok, media} -> attach_raw_file({:ok, photo}, media)
        {:error, _} = err -> err
      end
    end
  end

  @spec attach_raw_file({:ok, Photo.t()}, Media.t()) :: rc()
  defp attach_raw_file({:ok, %Photo{} = photo}, %Media{} = media) do
    with {:ok, file, dest_path} <-
           Storage.build_file_metadata(media, photo, "raw", check_conflicts: true),
         :ok <- Storage.copy_file(media, dest_path) do
      photo =
        photo
        |> Ecto.Changeset.change()
        |> Ecto.Changeset.put_assoc(:files, photo.files ++ [file])
        |> Repo.update!()

      {:ok, photo}
    else
      {:error, reason} ->
        {:error, reason}
    end
  end

  # ---------------------------------------------------------------------------
  # Status printing
  # ---------------------------------------------------------------------------

  @spec print_status(rc(), String.t()) :: rc()
  defp print_status({:ok, %Photo{} = photo} = rc, _path) do
    Logger.info("Done #{Photo.to_string(photo)}")

    Enum.each(photo.files, fn file ->
      Logger.info("     #{File.to_string(file)}")
    end)

    rc
  end

  defp print_status({:skipped, %Photo{} = photo} = rc, _path) do
    Logger.info("Skipped #{Photo.to_string(photo)}")

    Enum.each(photo.files, fn file ->
      Logger.info("     #{File.to_string(file)}")
    end)

    rc
  end

  defp print_status({:error, reason} = rc, path) do
    Logger.error("Error #{path}: #{reason}")
    rc
  end

  # ---------------------------------------------------------------------------
  # Public API: upload a single file
  # ---------------------------------------------------------------------------

  @spec upload_file(String.t(), Album.t(), keyword()) :: rc
  def upload_file(path, album, opts \\ []) do
    with {:ok, media} <- Media.get_media(path) do
      default_date = DateTime.now!("Australia/Melbourne") |> DateTime.to_date()
      upload_date = Keyword.get(opts, :date, default_date)
      timezone = Keyword.get(opts, :timezone, "Australia/Melbourne")
      filename = Keyword.get(opts, :filename, Path.basename(path))
      auto_rotate = Keyword.get(opts, :auto_rotate, false)

      exif = Media.get_exif(media)
      {file_timezone, offset} = get_camera_offset(exif["EXIF:Model"])

      utc_datetime =
        media
        |> Media.get_datetime()
        |> DateTime.from_naive!(file_timezone)
        |> DateTime.add(-offset)
        |> DateTime.shift_zone!("Etc/UTC")

      local_datetime = DateTime.shift_zone!(utc_datetime, timezone)

      size_key = "orig"
      photo_dir = Storage.build_photo_dir(upload_date)
      action = if auto_rotate, do: "auto", else: "R"

      photo = %Photo{
        dir: photo_dir,
        filename: filename,
        datetime: utc_datetime,
        utc_offset: trunc((local_datetime.utc_offset + local_datetime.std_offset) / 60),
        action: action
      }

      photo = add_exif_to_photo(photo, media)

      rc =
        {:ok, photo}
        |> check_file_conflicts(media, size_key)
        |> do_save(album, media, size_key)
        |> add_raw_files(path)
        |> print_status(path)

      case rc do
        {:ok, %Photo{}} = rc -> rc
        {:skipped, %Photo{}} = rc -> rc
        {:error, reason} -> {:error, "Error processing #{path}: #{reason}"}
      end
    end
  end

  @spec do_save(rc(), Album.t(), Media.t(), String.t()) :: rc()
  defp do_save({:skipped, _} = rc, _album, _media, _size_key), do: rc

  defp do_save({:ok, %Photo{} = photo}, %Album{} = album, %Media{} = media, size_key) do
    build_photo_multi(photo, album, media, size_key)
  end

  # ---------------------------------------------------------------------------
  # Album helpers
  # ---------------------------------------------------------------------------

  @spec get_parent_album() :: Album.t()
  def get_parent_album do
    case Repo.one(from a in Album, where: a.name == "Uploads") do
      nil ->
        %Album{name: "Uploads", sort_name: "Uploads"}
        |> Ecto.Changeset.change()
        |> Repo.insert!()

      album ->
        album
    end
  end

  @spec get_upload_album(String.t()) :: Album.t()
  def get_upload_album(name) do
    parent = get_parent_album()

    query =
      from a in Album,
        join: ap in AlbumParent,
        on: ap.album_id == a.id,
        where: ap.parent_id == ^parent.id and a.name == ^name

    case Repo.one(query) do
      nil ->
        album =
          %Album{
            name: name,
            sort_name: name,
            reindex: true
          }
          |> Ecto.Changeset.change()
          |> Repo.insert!()

        %AlbumParent{
          album_id: album.id,
          parent_id: parent.id,
          context_name: nil,
          context_sort_name: nil,
          context_cover_photo_id: nil
        }
        |> Ecto.Changeset.change()
        |> Repo.insert!()

        album

      %Album{} = album ->
        album
    end
  end

  # ---------------------------------------------------------------------------
  # Public API: upload a directory (CLI / IEx)
  # ---------------------------------------------------------------------------

  # Extensions that are handled as sidecars or metadata — not uploaded as
  # primary files. They are discovered automatically when the primary file
  # (e.g. JPG) is processed.
  @sidecar_extensions [".CR2", ".cr2", ".CR3", ".cr3", ".dng", ".pp3", ".xmp"]

  @spec upload_directory(String.t(), keyword()) :: list(Photo.t())
  def upload_directory(directory, opts \\ []) do
    default_date = DateTime.now!("Australia/Melbourne") |> DateTime.to_date()
    upload_date = Keyword.get(opts, :date, default_date)
    opts = Keyword.put(opts, :date, upload_date)

    album =
      directory
      |> Path.basename()
      |> get_upload_album()

    ls!(directory)
    |> Enum.sort()
    |> Enum.map(fn filename -> Path.join(directory, filename) end)
    |> Enum.reject(fn path ->
      dir?(path) or Path.extname(path) in @sidecar_extensions
    end)
    |> Enum.map(fn path ->
      case upload_file(path, album, opts) do
        {:ok, %Photo{} = photo} -> photo
        {:skipped, %Photo{} = photo} -> photo
        {:error, reason} -> raise reason
      end
    end)
  end
end
