name: Build and Deploy to Docker Hub

on:
  - push
  - pull_request

jobs:
  test:
    name: Setup, Build, Test
    uses: brianmay/workflows/.github/workflows/elixir.yaml@729c8dbd856b565b4d6ce3568dde46294b9f9ae7
    with:
      apt_packages: "libimage-exiftool-perl ffmpeg exiftran dcraw"
      test_data: "https://www.dropbox.com/s/yg6jdk9lfewn8yf/penguin_memories.tar?dl=0"

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    uses: brianmay/workflows/.github/workflows/docker.yaml@729c8dbd856b565b4d6ce3568dde46294b9f9ae7
    needs:
      - test
