name: Build and Deploy to Docker Hub

on:
  - push
  - pull_request

jobs:
  test:
    name: Setup, Build, Test
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      apt_packages: "libimage-exiftool-perl ffmpeg exiftran dcraw"
      test_data: "https://www.dropbox.com/s/yg6jdk9lfewn8yf/penguin_memories.tar?dl=0"

  push:
    name: Push
    uses: brianmay/workflows/.github/workflows/docker.yaml@main
    secrets:
      DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
    with:
      deploy_servers: true
    needs:
      - test
